### ISSUE TITLE
Issue a002

### ISSUE THREAD

**Issue by yanniqq** [spaebo/HelloWorld#3]
Füg mal n gescheites gitignore file für java projecte hinzu und erstell ein einfaches helloworld java programm

**Comment by PlebLex** [comment]
done

**Comment by yanniqq** [comment]
Seher nice

Am 11.02.2017 15:44 schrieb "PlebLex" <notifications@github.com>:

**Comment by PlebLex** [comment]
Antworten hier gehen direkt zu den Kommentaren der Issue, und das ist 
cool. Aber du solltest die Überbleibsel der vorherigen Nachricht 
weglassen. Die kommen sonst mit in die Issue, denke ich.

**Comment by yanniqq** [comment]
Ah OK. Das Feature ist sehr nice. Steht da dann iwie dabei "sent by E-Mail"
oder sieht man das sonst nicht?
(Btw jetzt sind alle zitierten vorherigen Nachrichten gelöscht)
